#!/usr/bin/ksh
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm $Tmp  >/dev/null 2>&1



#cp plugin/dir.vim   /home/mestes/.vim/bundle/vim-dir/plugin/dir.vim
#exit 0



#-------------------------------------------------------------------------------------
./tagit
git add functions.txt

echo "# vim-dir" > README.md
echo "" >> README.md
cat functions.txt  | gawk '{print "- " $0 }' >> README.md


git add plugin/dir.vim
git add pushit
git add README.md
git add tagit
git commit -m "Update"
git push -u origin master
REPO=vim-dir
rm -rf $HOME/.vim/bundle/$REPO
vim  -c ":PluginInstall! $REPO" -c ":qa!"
#-------------------------------------------------------------------------------------

